name: Rust Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-binary
          path: target/release/

  prepare_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: binaries

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/Ubuntu-latest-binary/*
            binaries/Windows-latest-binary/*
            binaries/macOS-latest-binary/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
